<a href="https://colab.research.google.com/github/qLuVik/labs_pda/blob/main/%D0%9A%D0%B0%D0%BF%D1%80%D0%B0%D0%BD%D0%BE%D0%B2%D0%B0_%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D0%BD%D0%B0_%D0%BB%D0%B5%D0%BA%D1%86%D0%B8%D0%B82.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

создание массива из списка

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
type(a)

Вычисление типа

In [ ]:
print(arr.dtype)

int64


In [ ]:
arr = np.array([1, 2, 3.14])
print(arr.dtype)

float64


форма массивов

In [ ]:
arr = np.array([1, 2, 3])
print(arr.shape)

(3,)


In [ ]:
b = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=np.complex)
b

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[1.5+0.j, 2. +0.j, 3. +0.j],
       [4. +0.j, 5. +0.j, 6. +0.j]])

Функция zeros() создает массив из нулей, а функция ones() — массив из единиц. Обе функции принимают кортеж с размерами, и аргумент dtype:

In [ ]:
np.zeros((3, 5))
np.ones((2, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

единичная матрица (двумерный массив)

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Функция empty() создает массив без его заполнения. Исходное содержимое случайно и зависит от состояния памяти на момент создания массива (то есть от того мусора, что в ней хранится):

In [ ]:
np.empty((3, 3))
np.empty((3, 3))

array([[4.66652352e-310, 3.60739284e-313, 1.38338381e-322],
       [4.66652352e-310, 0.00000000e+000, 0.00000000e+000],
       [4.94065646e-323, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

fromfunction(): применяет функцию ко всем комбинациям индексов

In [ ]:
def f1(i, j):
    return 3 * i + j

print(np.fromfunction(f1, (3, 4)))
print(np.fromfunction(f1, (3, 3)))

[[0. 1. 2. 3.]
 [3. 4. 5. 6.]
 [6. 7. 8. 9.]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a.shape)

(3, 2)


In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a.size)

6


In [ ]:
print(np.arange(0,3000,1))

[   0    1    2 ... 2997 2998 2999]


In [ ]:
import sys
import numpy as np

a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a + b)
print(a - b)
print(a * b)
print(a / b)  
print(a ** b)
print(a % b) 

[20 31 42 53]
[20 29 38 47]
[  0  30  80 150]
[        inf 30.         20.         16.66666667]
[     1     30   1600 125000]
[0 0 0 2]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in remainder
  # This is added back by InteractiveShellApp.init_path()


In [ ]:
print(a + 1)
print(a ** 3)
print(a < 35)

[21 31 41 51]
[  8000  27000  64000 125000]
[ True  True False False]


In [ ]:
print(np.cos(a))
print(np.arctan(a))
print(np.sinh(a))

[ 0.40808206  0.15425145 -0.66693806  0.96496603]
[1.52083793 1.53747533 1.54580153 1.55079899]
[2.42582598e+08 5.34323729e+12 1.17692633e+17 2.59235276e+21]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a))
print(a.sum())
print(a.min())
print(a.max())

21
21
1
6


In [ ]:
a = np.arange(10) ** 3
print(a)
print(a[1])
print(a[3:7])
a[3:7] = 8
print(a)
print(a[::-1])


for i in a:
    print(i ** (1/3))

In [ ]:
b = np.array([[  0, 1, 2, 3],
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])

print(b[2,3]) 
print(b[(2,3)])
print(b[2][3]) 
print(b[:,2]) 
print(b[:2]) 
print(b[1:3, : : ])  

23
23
23
[ 2 12 22 32 42]
[[ 0  1  2  3]
 [10 11 12 13]]
[[10 11 12 13]
 [20 21 22 23]]


у массива есть форма (shape), определяемая числом элементов вдоль каждой оси:

In [ ]:
a
a.shape

(4,)

Форма массива может быть изменена с помощью различных команд:

In [ ]:
a = np.array(([[0, 1, 2], [10, 12, 13]], [[100, 101, 102], [110, 112, 113]]))
print(a.ravel())  # Делает массив плоским
a.shape = (6, 2)  # Изменение формы
print(a)
print(a.transpose())  # Транспонирование
print(a.reshape((3, 4)))  # Изменение формы

[  0   1   2  10  12  13 100 101 102 110 112 113]
[[  0   1]
 [  2  10]
 [ 12  13]
 [100 101]
 [102 110]
 [112 113]]
[[  0   2  12 100 102 112]
 [  1  10  13 101 110 113]]
[[  0   1   2  10]
 [ 12  13 100 101]
 [102 110 112 113]]


hstack() объединяет массивы по первым осям, vstack() — по последним:

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


Функция column_stack() объединяет одномерные массивы в качестве столбцов двумерного массива:

In [ ]:
np.column_stack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Аналогично для строк имеется функция row_stack()

In [ ]:
np.row_stack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Разбиение массива

In [ ]:
import numpy as np
import random
np.array([random.random() for i in range(10)])

array([0.81090758, 0.51483618, 0.91839707, 0.05667428, 0.09251946,
       0.9635855 , 0.67488232, 0.31343958, 0.68298334, 0.98283773])

In [ ]:
import numpy as np  
np.random
import numpy.random as rand  
rand

<module 'numpy.random' from '/usr/local/lib/python3.7/dist-packages/numpy/random/__init__.py'>

In [ ]:
print(np.random.sample())
print(np.random.sample(3))
print(np.random.sample((2, 3)))

0.3071226720390653
[0.36709182 0.66385995 0.9779709 ]
[[0.83057832 0.50129848 0.59046056]
 [0.936954   0.3350889  0.87782876]]


In [ ]:
print(np.random.randint(0, 3, 10))
print(np.random.random_integers(0, 3, 10))
print(np.random.randint(0, 3, (2, 10)))

[2 0 1 1 0 0 0 1 2 2]
[1 1 3 2 0 1 3 0 1 0]
[[1 2 0 0 1 0 1 1 1 2]
 [2 1 0 0 1 0 0 2 2 0]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 3 + 1) instead
  


# Новый раздел

In [ ]:
import timeit 
start_time = timeit.default_timer()
function_1()
time_1 = timeit.default_timer() - start_time
start_time = timeit.default_timer()
function_2()
time_2 = timeit.default_timer() - start_time
print('Function 1 took', time_1)
print('Function 2 took', time_2)

In [ ]:
import timeit 
import numpy as np

def time_range(size): 
  for i in range(size): 
    pass 

def time_arange(size):
   np.arange(size)

if __name__ == '__main__': 
     

    start_time = timeit.default_timer();
    time_range(1000) 
    range_time_1 = timeit.default_timer() - start_time 

    start_time = timeit.default_timer(); 
    time_arange(1000) 
    arange_time_1 = timeit.default_timer() - start_time 

    start_time = timeit.default_timer(); 
    time_range(1000000000) 
    range_time_2 = timeit.default_timer() - start_time 

    start_time = timeit.default_timer(); 
    time_arange(1000000000) 
    arange_time_2 = timeit.default_timer() - start_time 

In [ ]:
print('Array size: 1000') 

print(f'size 1000: range() время {range_time_1}') 
print(f'size 1000: arange() время {arange_time_1}') 

print('Array size: 1000000') 
print(f'size 1000000: range() время {range_time_2}') 
print(f'size 1000000: arange() время {arange_time_2}')

Array size: 1000
size 1000: range() время 2.695599999924525e-05
size 1000: arange() время 1.918399999567555e-05
Array size: 1000000
size 1000000: range() время 24.376710984
size 1000000: arange() время 0.8506327519999957
