<a href="https://colab.research.google.com/github/qLuVik/labs_pda/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [ ]:
#1.1
n = int(input())
Z = np.zeros(n)
print(Z)

5
[0. 0. 0. 0. 0.]


In [ ]:
#1.2
print(Z.nbytes)

40


In [ ]:
#1.3
n = int(input())
x = int(input())
Z = np.zeros(n)
Z[x] = 1

10
4


In [ ]:
#1.4
n = int(input())
m = int(input())
Z = np.arange(n,m+1)
#print(Z)

10
50


In [ ]:
#1.5
Z = Z[::-1]
#print(Z)

In [ ]:
#1.6
n = int(input())
m,k = map(int,input().split())

Z = np.arange(0,n).reshape(m,k)
#print(Z)

6
2 3


In [ ]:
#1.7
NonZerros = np.nonzero(Z)
#print(NonZerros)

In [ ]:
#1.8
n = int(input())
Z = np.eye(n)
#print(Z)

3


In [ ]:
#1.9
n,m,l = map(int,input().split())
np.random.seed(42)
Z = np.random.random((n,m,l))
#print(Z)

2 2 2


In [ ]:
#1.10
n,m = map(int,input().split())
np.random.seed(42)
Z = np.random.random((n,m))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

10 10
0.005522117123602399 0.9868869366005173


In [ ]:
#1.11
n,m = map(int,input().split())
np.random.seed(42)
Z = np.random.random((n,m))
d = Z.mean()
print(d)

30 30
0.4923750160905882


In [ ]:
#1.12
A = np.array([1.5, 2.5, 3.5])
B = np.array([4, 5, 6])
Z = np.dot(A,B)
print(Z)

39.5


In [ ]:
#1.13
A = np.array([
 [1, 2, 3],
 [4, 5, 6]
])
B = np.array([
 [11.5],
 [12.5],
 [13.5]
])
try:
    Z = np.dot(A, B)
except ValueError:
        Z= "Упс! Что-то пошло не так..."
else:
     Z = np.dot(A, B)
#print(Z)

In [ ]:
#1.14
Z = np.arange(11)
Z[(3<Z)&(Z<9)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
#1.15
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
Z = np.prod(np.diag(X)[np.diag(X)!=0] )
print(Z)

3


In [ ]:
#1.16
n = float(input())
Z = np.arange(0,n)*0
print(Z)

5
[0. 0. 0. 0. 0.]


In [ ]:
#1.17
Z = np.zeros((10,10))
print(Z.itemsize*Z.size)

800


In [ ]:
#1.19
Z = np.array(range(int(input()), int(input()) + 1))

10
50


In [ ]:
#1.20
Z = np.flip(Z, 0)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [13]:
#1.22
Z = np.array([1,0,2,0,3,0,4])
NonZerros = np.where(np.array(Z)>0)
print(NonZerros)

(array([0, 2, 4, 6]),)


In [14]:
#1.23
n = int(input())

Z = np.identity(n)
#print(Z)

3


In [22]:
#1.24
np.random.seed(42)

n, m, l, = map(int, input().split())

Z = np.random.rand(n*m*l).reshape(n,m,l)
#prin(Z)

2 2 2


In [21]:
#1.25
np.random.seed(42)
n, m = input().split()
Z = np.random.rand(int(n), int(m))
print(np.min(Z))
print(np.max(Z))

10 10
0.005522117123602399
0.9868869366005173


In [19]:
import timeit
start_time = timeit.default_timer()

n = int(input())
Z = np.zeros(n)
print(Z)

time_1 = timeit.default_timer() - start_time
start_time = timeit.default_timer()

n = float(input())
Z = np.arange(0,n)*0
print(Z)

time_2 = timeit.default_timer() - start_time
print('Первая функиця', time_1)
print('Вторая функция', time_2)

5
[0. 0. 0. 0. 0.]
5
[0. 0. 0. 0. 0.]
Первая функиця 6.025417636999919
Вторая функция 2.2950782400002936


In [20]:
import timeit
start_time = timeit.default_timer()
n,m = map(int,input().split())

np.random.seed(42)
Z = np.random.random((n,m))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

time_1 = timeit.default_timer() - start_time
start_time = timeit.default_timer()

np.random.seed(42)
n, m = input().split()
Z = np.random.rand(int(n), int(m))
print(np.min(Z))
print(np.max(Z))

time_2 = timeit.default_timer() - start_time
print('Первая функиця', time_1)
print('Вторая функция', time_2)

10 10
0.005522117123602399 0.9868869366005173
10 10
0.005522117123602399
0.9868869366005173
Первая функиця 2.632569065000098
Вторая функция 4.978213227999731
